config/routes.rb
Rails.application.routes.draw do
  resources :meetings, only: [ :index, :show ]
  resources :join_infos, only: [ :index, :show ]
  resources :locations, only: [ :index, :show ]
  resources :recovery_communities, only: [ :index, :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/join_info.rb
class JoinInfo < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :recovery_community
  belongs_to :location, optional: true
  belongs_to :join_info, optional: true
end

app/models/recovery_community.rb
class RecoveryCommunity < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/join_infos_controller.rb
class JoinInfosController < ApplicationController
  before_action :set_join_info, only: %i[ show ]

  # GET /join_infos or /join_infos.json
  def index
    @join_infos = JoinInfo.all
  end

  # GET /join_infos/1 or /join_infos/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_join_info
      @join_info = JoinInfo.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def join_info_params
      params.expect(join_info: [ :link, :meeting_id, :meeting_provider, :password ])
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show ]

  # GET /locations or /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.expect(location: [ :street_address, :province, :country, :lat, :long ])
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show ]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1 or /meetings/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.expect(meeting: [ :source, :time, :type, :recovery_community_id, :location_id, :join_info_id ])
    end
end

app/controllers/recovery_communities_controller.rb
class RecoveryCommunitiesController < ApplicationController
  before_action :set_recovery_community, only: %i[ show ]

  # GET /recovery_communities or /recovery_communities.json
  def index
    @recovery_communities = RecoveryCommunity.all
  end

  # GET /recovery_communities/1 or /recovery_communities/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recovery_community
      @recovery_community = RecoveryCommunity.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def recovery_community_params
      params.expect(recovery_community: [ :name, :description, :acronym ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/join_infos_helper.rb
module JoinInfosHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/recovery_communities_helper.rb
module RecoveryCommunitiesHelper
end

app/views/join_infos/_join_info.html.erb
<div id="<%= dom_id join_info %>">
  <p>
    <strong>Link:</strong>
    <%= join_info.link %>
  </p>

  <p>
    <strong>Meeting:</strong>
    <%= join_info.meeting_id %>
  </p>

  <p>
    <strong>Meeting provider:</strong>
    <%= join_info.meeting_provider %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= join_info.password %>
  </p>

</div>

app/views/join_infos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Join infos" %>

<h1>Join infos</h1>

<div id="join_infos">
  <% @join_infos.each do |join_info| %>
    <%= render join_info %>
    <p>
      <%= link_to "Show this join info", join_info %>
    </p>
  <% end %>
</div>

<%= link_to "New join info", new_join_info_path %>

app/views/join_infos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @join_info %>

<div>
  <%= link_to "Edit this join info", edit_join_info_path(@join_info) %> |
  <%= link_to "Back to join infos", join_infos_path %>

  <%= button_to "Destroy this join info", @join_info, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Meeting Finder" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>">
  <p>
    <strong>Street address:</strong>
    <%= location.street_address %>
  </p>

  <p>
    <strong>Province:</strong>
    <%= location.province %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= location.country %>
  </p>

  <p>
    <strong>Lat:</strong>
    <%= location.lat %>
  </p>

  <p>
    <strong>Long:</strong>
    <%= location.long %>
  </p>

</div>

app/views/locations/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Locations" %>

<h1>Locations</h1>

<div id="locations">
  <% @locations.each do |location| %>
    <%= render location %>
    <p>
      <%= link_to "Show this location", location %>
    </p>
  <% end %>
</div>

<%= link_to "New location", new_location_path %>

app/views/locations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @location %>

<div>
  <%= link_to "Edit this location", edit_location_path(@location) %> |
  <%= link_to "Back to locations", locations_path %>

  <%= button_to "Destroy this location", @location, method: :delete %>
</div>

app/views/meetings/_meeting.html.erb
<div id="<%= dom_id meeting %>">
  <p>
    <strong>Source:</strong>
    <%= meeting.source %>
  </p>

  <p>
    <strong>Time:</strong>
    <%= meeting.time %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= meeting.type %>
  </p>

  <p>
    <strong>Recovery community:</strong>
    <%= meeting.recovery_community_id %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= meeting.location_id %>
  </p>

  <p>
    <strong>Join info:</strong>
    <%= meeting.join_info_id %>
  </p>

</div>

app/views/meetings/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Meetings" %>

<h1>Meetings</h1>

<div id="meetings">
  <% @meetings.each do |meeting| %>
    <%= render meeting %>
    <p>
      <%= link_to "Show this meeting", meeting %>
    </p>
  <% end %>
</div>

<%= link_to "New meeting", new_meeting_path %>

app/views/meetings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @meeting %>

<div>
  <%= link_to "Edit this meeting", edit_meeting_path(@meeting) %> |
  <%= link_to "Back to meetings", meetings_path %>

  <%= button_to "Destroy this meeting", @meeting, method: :delete %>
</div>

app/views/recovery_communities/_recovery_community.html.erb
<div id="<%= dom_id recovery_community %>">
  <p>
    <strong>Name:</strong>
    <%= recovery_community.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recovery_community.description %>
  </p>

  <p>
    <strong>Acronym:</strong>
    <%= recovery_community.acronym %>
  </p>

</div>

app/views/recovery_communities/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Recovery communities" %>

<h1>Recovery communities</h1>

<div id="recovery_communities">
  <% @recovery_communities.each do |recovery_community| %>
    <%= render recovery_community %>
    <p>
      <%= link_to "Show this recovery community", recovery_community %>
    </p>
  <% end %>
</div>

app/views/recovery_communities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recovery_community %>

<div>
  <%= link_to "Back to recovery communities", recovery_communities_path %>
</div>